# $FreeBSD$

FILES=	com.apple.notifyd.json \
	com.apple.syslogd.json \
	org.freebsd.getty.ttyv0.json \
	org.freebsd.getty.ttyv1.json \
	org.freebsd.getty.ttyv2.json \
	org.freebsd.getty.ttyv3.json \
	org.freebsd.devd.json
NO_OBJ=
FILESDIR= /etc/launchd.d

.include <bsd.prog.mk>
