# $FreeBSD$

.include <bsd.own.mk>

NO_OBJ=
INCS=	_OSByteOrder.h \
	OSAtomic.h \
	OSByteOrder.h \
	OSCacheControl.h \
	OSDebug.h \
	OSKextLib.h \
	OSReturn.h \
	OSThermalNotification.h \
	OSTypes.h
INCSDIR=${INCLUDEDIR}/libkern

.include <bsd.prog.mk>
